# Generated by Django 2.2 on 2019-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_CRN',
            field=models.PositiveIntegerField(default=0, help_text='Enter your course CRN:'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_credits',
            field=models.PositiveIntegerField(default=0, help_text='Enter course credits:'),
        ),
    ]
