# Generated by Django 2.2 on 2019-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.CharField(max_length=6)),
                ('name', models.CharField(help_text='Enter course name:', max_length=30)),
                ('credits', models.PositiveIntegerField(default=0, help_text='Enter course credits:')),
                ('professor', models.CharField(help_text='Enter professor name:', max_length=30)),
                ('location', models.CharField(help_text='Enter location:', max_length=50)),
                ('time', models.CharField(help_text='Enter time of class:', max_length=30)),
                ('day', models.DateTimeField(help_text='Enter day(s) of class:')),
            ],
        ),
    ]
