# Generated by Django 2.2 on 2019-06-03 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.CharField(max_length=6)),
                ('name', models.CharField(help_text='Enter course name:', max_length=30)),
                ('credits', models.PositiveIntegerField(default=0, help_text='Enter course credits:')),
                ('professor', models.CharField(help_text='Enter professor name:', max_length=30)),
                ('location', models.CharField(help_text='Enter location:', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frequency_of_course', models.ManyToManyField(to='mycalendar.DaysOfTheWeek')),
            ],
        ),
    ]
