# Generated by Django 2.2 on 2019-05-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='time',
        ),
    ]
