# Generated by Django 2.2 on 2019-06-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
