# Generated by Django 2.2 on 2019-05-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_remove_classes_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
