# Generated by Django 2.2 on 2019-05-24 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycalendar', '0003_delete_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.CharField(max_length=6)),
                ('name', models.CharField(help_text='Enter course name:', max_length=30)),
                ('credits', models.PositiveIntegerField(default=0, help_text='Enter course credits:')),
                ('professor', models.CharField(help_text='Enter professor name:', max_length=30)),
                ('location', models.CharField(help_text='Enter location:', max_length=50)),
                ('day', models.DateTimeField(help_text='Enter day(s) of class:')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
