# Generated by Django 2.2 on 2019-05-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
